print("Forget to add endpoint in github webhook workflow!")
print("Testing merge request from feature-merge-test branch")
print("Triggering push webhook!")
print("Testing merge request from feature-merge-test branch")
print("Triggering push webhook!")